<?php

declare(strict_types=1);

namespace OpenEMR\Modules\ClinicalCopilot\Controller;

use OpenEMR\Common\Acl\AclMain;
use OpenEMR\Common\Csrf\CsrfUtils;
use OpenEMR\Common\Logging\EventAuditLogger;
use OpenEMR\Common\Session\SessionWrapperFactory;

/**
 * PHP bridge for the Clinical Co-Pilot chat panel.
 *
 * This controller is the security gatekeeper between the browser and the AI service.
 * It runs inside OpenEMR's PHP runtime, which means it has access to the session,
 * database, and all of OpenEMR's auth infrastructure. The Python service does not —
 * which is exactly why this layer exists.
 *
 * Request flow:
 *   Browser (fetch POST) → public/ajax.php → ChatController::handleRequest()
 *       → [validate] → [audit log] → callAiService() → Python /chat → JSON response
 *
 * The AI service URL defaults to http://ai:8001 (Docker service name on the shared
 * network). Override with the AI_SERVICE_URL environment variable for other envs.
 */
class ChatController
{
    private string $authUser;
    private string $authProvider;
    private int $authUserID;

    public function __construct()
    {
        // Read identity from the current OpenEMR session.
        // These values are set by OpenEMR's login flow and cannot be forged
        // by the browser — they live server-side in the PHP session.
        $session = SessionWrapperFactory::getInstance()->getActiveSession();
        $this->authUser     = (string)($session->get('authUser')     ?? '');
        $this->authProvider = (string)($session->get('authProvider') ?? '');
        $this->authUserID   = (int)($session->get('authUserID')       ?? 0);
    }

    public function handleRequest(): void
    {
        $session = SessionWrapperFactory::getInstance()->getActiveSession();

        // ── GUARD 1: CSRF Token ──────────────────────────────────────────────────
        // The CSRF token is generated by OpenEMR's main.php and stored in the JS
        // variable `csrf_token_js`. Our chat panel appends it to every POST request.
        // If the token is missing or wrong, someone is either:
        //   (a) calling our endpoint directly without going through the chat panel, or
        //   (b) attempting a cross-site request forgery attack.
        // Either way, we reject the request immediately.
        if (!CsrfUtils::verifyCsrfToken(
            $_POST['csrf_token_form'] ?? $_GET['csrf_token_form'] ?? '',
            session: $session
        )) {
            $this->sendError('CSRF verification failed.', 403);
            return;
        }

        // ── GUARD 2: Authenticated Session ──────────────────────────────────────
        // authUserID = 0 means either no session exists or the session has expired.
        // This prevents the endpoint from being hit by logged-out requests.
        if ($this->authUserID <= 0) {
            $this->sendError('Not authenticated.', 401);
            return;
        }

        // ── GUARD 3: ACL Permission ──────────────────────────────────────────────
        // 'patients','demo' is OpenEMR's permission for viewing patient demographics —
        // the minimum required to surface any patient context. Nurses, physicians, and
        // admins typically have this. A user without it should not be able to query the
        // AI about a patient at all.
        if (!AclMain::aclCheckCore('patients', 'demo')) {
            $this->sendError('Access denied: insufficient permissions.', 403);
            return;
        }

        // ── GUARD 4: Patient ID — use SESSION, not POST ──────────────────────────
        // The browser sends `pid` in the POST body as a convenience, but we never
        // trust it. The authoritative pid is what OpenEMR's PatientSessionUtil set
        // in the session when the physician opened the patient chart. This prevents
        // a malicious or misconfigured client from querying a different patient's data.
        $pid = intval($session->get('pid') ?? 0);

        // ── GUARD 5: Message Validation ──────────────────────────────────────────
        $message = trim($_POST['message'] ?? '');
        if (empty($message)) {
            $this->sendError('Message is required.', 400);
            return;
        }
        // strip_tags removes any HTML the user might try to inject.
        // The message is passed as plain text to the AI — it is never rendered as HTML.
        $message = strip_tags($message);
        // Hard cap: prevents unusually large payloads from reaching the AI service.
        if (strlen($message) > 500) {
            $message = substr($message, 0, 500);
        }

        // ── AUDIT LOG ────────────────────────────────────────────────────────────
        // HIPAA §164.312(b) requires logging all access to PHI.
        // We log the action category ("patient-query"), NOT the message text.
        // Logging the actual question would write PHI into the audit trail
        // (e.g., "Is this patient's Metformin causing their kidney issue?").
        // The audit record only needs to show: who, which patient, when, what type of access.
        EventAuditLogger::getInstance()->newEvent(
            'ai-copilot-query',  // event type — searchable in the audit log
            $this->authUser,     // the logged-in username
            $this->authProvider, // their provider group
            1,                   // success flag (1 = success; we log before processing)
            'patient-query',     // category label — no PHI here
            $pid,                // which patient was accessed
            'open-emr',          // source system identifier
            'ai-copilot'         // which feature within OpenEMR
        );

        // ── HMAC INTERNAL TOKEN ───────────────────────────────────────────────────
        // Generate a short-lived token so the Python service can call back to our
        // internal api.php to fetch patient data. The signature covers "{pid}:{ts}"
        // so a token for this patient cannot be replayed for a different pid, and
        // it expires in 30 seconds — tight enough to prevent replay attacks while
        // giving the LLM plenty of time to respond.
        $ts            = time();
        $hmacSecret    = (string)(getenv('COPILOT_HMAC_SECRET') ?: 'dev-hmac-secret');
        $sig           = hash_hmac('sha256', "{$pid}:{$ts}", $hmacSecret);
        $internalToken = "{$ts}:{$sig}";

        // ── CALL AI SERVICE ──────────────────────────────────────────────────────
        // All guards have passed. Forward to Python with the HMAC token so tools
        // can call back to api.php and fetch real patient data.
        $aiResponse = $this->callAiService($pid, $this->authUser, $message, $internalToken);
        $this->sendSuccess($aiResponse);
    }

    /**
     * Make an HTTP POST to the Python AI service and return a normalised response array.
     *
     * Failure modes handled here (never let an exception reach the browser):
     *   - Connection refused / DNS failure  → service unreachable message
     *   - Timeout (>10s)                    → timeout message
     *   - Non-200 HTTP status from Python   → surface the error body
     *   - Response body is not valid JSON   → generic error message
     *
     * We intentionally do NOT log the message or the response here — both can
     * contain PHI. The audit log entry (written above) captures access metadata only.
     *
     * @param int    $pid      Patient ID (from session, already validated)
     * @param string $authUser OpenEMR username (from session)
     * @param string $message  Sanitized physician question
     * @return array<string, mixed> Normalised response ready for sendSuccess()
     */
    private function callAiService(int $pid, string $authUser, string $message, string $internalToken): array
    {
        // AI_SERVICE_URL env var lets us point at a different host in production
        // without changing code. Default is the Docker service name on the shared network.
        $baseUrl = rtrim((string)(getenv('AI_SERVICE_URL') ?: 'http://ai:8001'), '/');
        $endpoint = $baseUrl . '/chat';

        // Build the JSON payload that matches app/models/chat.py → ChatRequest.
        // internal_token lets Python tools call back to api.php to fetch patient data.
        // It is scoped to this pid and expires in 30 seconds.
        $payload = json_encode([
            'pid'            => $pid,
            'auth_user'      => $authUser,
            'message'        => $message,
            'internal_token' => $internalToken,
        ]);

        // ── cURL setup ───────────────────────────────────────────────────────────
        // We use cURL directly (no Guzzle) because it's always available in PHP
        // and gives us precise control over timeouts without extra dependencies.
        $ch = curl_init($endpoint);
        curl_setopt_array($ch, [
            CURLOPT_POST           => true,
            CURLOPT_POSTFIELDS     => $payload,
            CURLOPT_HTTPHEADER     => ['Content-Type: application/json', 'Accept: application/json'],
            CURLOPT_RETURNTRANSFER => true,   // return response as string, don't print it
            // CONNECTTIMEOUT: how long to wait while establishing the TCP connection.
            // 3s is generous for an internal Docker network — if it takes longer the
            // service is either down or severely overloaded.
            CURLOPT_CONNECTTIMEOUT => 3,
            // TIMEOUT: total max time for the entire request (connect + transfer).
            // Our latency budget is <5s for the AI response; 10s gives headroom for
            // a slow LLM call without hanging the physician's browser indefinitely.
            CURLOPT_TIMEOUT        => 10,
        ]);

        $rawResponse = curl_exec($ch);
        $httpCode    = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlErrno   = curl_errno($ch);
        $curlError   = curl_error($ch);
        // Note: curl_close() is deprecated since PHP 8.5 (no-op since 8.0).
        // The handle is freed automatically when $ch goes out of scope.

        // ── Handle cURL-level failures ────────────────────────────────────────────
        // These happen before any HTTP response is received: the service is down,
        // the hostname doesn't resolve, or the connection timed out.
        if ($rawResponse === false || $curlErrno !== 0) {
            // CURLE_OPERATION_TIMEDOUT = 28
            $isTimeout = ($curlErrno === 28);
            return [
                'answer'    => $isTimeout
                    ? 'The AI service took too long to respond. Please try again.'
                    : 'The AI service is temporarily unavailable. Please try again.',
                'citations' => [],
                'status'    => 'fail',
                'warnings'  => [$curlError],
            ];
        }

        // ── Parse the JSON body ───────────────────────────────────────────────────
        $decoded = json_decode($rawResponse, true);

        if (!is_array($decoded)) {
            // Response arrived but isn't valid JSON — Python crashed mid-response
            // or something upstream (nginx, Docker) returned an HTML error page.
            return [
                'answer'    => 'The AI service returned an unexpected response.',
                'citations' => [],
                'status'    => 'fail',
                'warnings'  => ['Non-JSON response from AI service (HTTP ' . $httpCode . ')'],
            ];
        }

        // ── Handle non-200 HTTP status codes ─────────────────────────────────────
        // 422 = Pydantic validation error (payload shape mismatch — our bug)
        // 500 = unhandled exception in Python (caught by global_exception_handler)
        if ($httpCode !== 200) {
            return [
                'answer'    => $decoded['answer'] ?? 'The AI service returned an error.',
                'citations' => [],
                'status'    => 'fail',
                'warnings'  => $decoded['warnings'] ?? ['AI service error (HTTP ' . $httpCode . ')'],
            ];
        }

        // ── Success — normalise the response fields ───────────────────────────────
        // Use null-coalescing defaults so a partial Python response never causes
        // PHP notices or undefined-index errors that would break the JSON output.
        return [
            'answer'    => (string)($decoded['answer']              ?? ''),
            'citations' => (array)($decoded['citations']            ?? []),
            'status'    => (string)($decoded['verification_status'] ?? 'pass'),
            'warnings'  => (array)($decoded['warnings']             ?? []),
        ];
    }

    // ── Helpers ──────────────────────────────────────────────────────────────────

    private function sendSuccess(array $data): void
    {
        header('Content-Type: application/json');
        echo json_encode(array_merge(['success' => true], $data));
    }

    private function sendError(string $message, int $httpCode = 400): void
    {
        http_response_code($httpCode);
        header('Content-Type: application/json');
        echo json_encode(['success' => false, 'error' => $message]);
    }
}
