<?php

declare(strict_types=1);

namespace OpenEMR\Modules\ClinicalCopilot\Controller;

use OpenEMR\Common\Acl\AclMain;
use OpenEMR\Common\Csrf\CsrfUtils;
use OpenEMR\Common\Logging\EventAuditLogger;
use OpenEMR\Common\Session\SessionWrapperFactory;

/**
 * PHP bridge for the Clinical Co-Pilot chat panel.
 *
 * This controller is the security gatekeeper between the browser and the AI service.
 * It runs inside OpenEMR's PHP runtime, which means it has access to the session,
 * database, and all of OpenEMR's auth infrastructure. The Python service does not —
 * which is exactly why this layer exists.
 *
 * Request flow:
 *   Browser (fetch POST) → public/ajax.php → ChatController::handleRequest()
 *       → [validate] → [audit log] → stub response (Step 1)
 *       → [Python service call added in Step 3]
 */
class ChatController
{
    private string $authUser;
    private string $authProvider;
    private int $authUserID;

    public function __construct()
    {
        // Read identity from the current OpenEMR session.
        // These values are set by OpenEMR's login flow and cannot be forged
        // by the browser — they live server-side in the PHP session.
        $session = SessionWrapperFactory::getInstance()->getActiveSession();
        $this->authUser     = (string)($session->get('authUser')     ?? '');
        $this->authProvider = (string)($session->get('authProvider') ?? '');
        $this->authUserID   = (int)($session->get('authUserID')       ?? 0);
    }

    public function handleRequest(): void
    {
        $session = SessionWrapperFactory::getInstance()->getActiveSession();

        // ── GUARD 1: CSRF Token ──────────────────────────────────────────────────
        // The CSRF token is generated by OpenEMR's main.php and stored in the JS
        // variable `csrf_token_js`. Our chat panel appends it to every POST request.
        // If the token is missing or wrong, someone is either:
        //   (a) calling our endpoint directly without going through the chat panel, or
        //   (b) attempting a cross-site request forgery attack.
        // Either way, we reject the request immediately.
        if (!CsrfUtils::verifyCsrfToken(
            $_POST['csrf_token_form'] ?? $_GET['csrf_token_form'] ?? '',
            session: $session
        )) {
            $this->sendError('CSRF verification failed.', 403);
            return;
        }

        // ── GUARD 2: Authenticated Session ──────────────────────────────────────
        // authUserID = 0 means either no session exists or the session has expired.
        // This prevents the endpoint from being hit by logged-out requests.
        if ($this->authUserID <= 0) {
            $this->sendError('Not authenticated.', 401);
            return;
        }

        // ── GUARD 3: ACL Permission ──────────────────────────────────────────────
        // 'patients','demo' is OpenEMR's permission for viewing patient demographics —
        // the minimum required to surface any patient context. Nurses, physicians, and
        // admins typically have this. A user without it should not be able to query the
        // AI about a patient at all.
        if (!AclMain::aclCheckCore('patients', 'demo')) {
            $this->sendError('Access denied: insufficient permissions.', 403);
            return;
        }

        // ── GUARD 4: Patient ID — use SESSION, not POST ──────────────────────────
        // The browser sends `pid` in the POST body as a convenience, but we never
        // trust it. The authoritative pid is what OpenEMR's PatientSessionUtil set
        // in the session when the physician opened the patient chart. This prevents
        // a malicious or misconfigured client from querying a different patient's data.
        $pid = intval($session->get('pid') ?? 0);

        // ── GUARD 5: Message Validation ──────────────────────────────────────────
        $message = trim($_POST['message'] ?? '');
        if (empty($message)) {
            $this->sendError('Message is required.', 400);
            return;
        }
        // strip_tags removes any HTML the user might try to inject.
        // The message is passed as plain text to the AI — it is never rendered as HTML.
        $message = strip_tags($message);
        // Hard cap: prevents unusually large payloads from reaching the AI service.
        if (strlen($message) > 500) {
            $message = substr($message, 0, 500);
        }

        // ── AUDIT LOG ────────────────────────────────────────────────────────────
        // HIPAA §164.312(b) requires logging all access to PHI.
        // We log the action category ("patient-query"), NOT the message text.
        // Logging the actual question would write PHI into the audit trail
        // (e.g., "Is this patient's Metformin causing their kidney issue?").
        // The audit record only needs to show: who, which patient, when, what type of access.
        EventAuditLogger::getInstance()->newEvent(
            'ai-copilot-query',  // event type — searchable in the audit log
            $this->authUser,     // the logged-in username
            $this->authProvider, // their provider group
            1,                   // success flag (1 = success; we log before processing)
            'patient-query',     // category label — no PHI here
            $pid,                // which patient was accessed
            'open-emr',          // source system identifier
            'ai-copilot'         // which feature within OpenEMR
        );

        // ── RESPONSE (Step 1 stub) ────────────────────────────────────────────────
        // In Step 1 we echo the message back to confirm the full pipeline works:
        //   Browser → PHP validation → audit log → JSON response → UI renders it.
        // This stub is replaced with the Python service call in Step 3.
        $this->sendSuccess([
            'answer'    => 'Echo: ' . $message,
            'citations' => [],
            'status'    => 'pass',
            'warnings'  => [],
        ]);
    }

    // ── Helpers ──────────────────────────────────────────────────────────────────

    private function sendSuccess(array $data): void
    {
        header('Content-Type: application/json');
        echo json_encode(array_merge(['success' => true], $data));
    }

    private function sendError(string $message, int $httpCode = 400): void
    {
        http_response_code($httpCode);
        header('Content-Type: application/json');
        echo json_encode(['success' => false, 'error' => $message]);
    }
}
